apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dasharr-config
  labels:
    app.kubernetes.io/name: dasharr
    app.kubernetes.io/part-of: dasharr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
