apiVersion: v1
kind: PersistentVolume
metadata:
  name: soulsync-nas-pv
  labels:
    app.kubernetes.io/part-of: soulsync
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-soulsync
  nfs:
    server: 192.168.1.162
    path: /volume1/docker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soulsync-media
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: soulsync
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-soulsync
  resources:
    requests:
      storage: 200Gi
  volumeName: soulsync-nas-pv
