# ghcr push credentials for the buildah step (PAT scope: write:packages).
# Pull side is a separate, read-only secret in the card-sniper namespace.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-push-secret
  namespace: card-sniper-ci
spec:
  encryptedData:
    .dockerconfigjson: AgC7n03QVIVmN+4YRt2Ef4sgziZq/+zOq3KGZoLcvK+zn4W8ZpJxg0cXSz8dGbBqqoqoMXXL0+14CSDc9rav528GRtGbpOdHhs7gfnVKpA9a+rgnJCk7t0kcDg9P3lU7a1+/mopfVGM9hpGiVtoM0YUS9xBrQibrwTv+pmV6rKiAx1PekzAaj1pO4Yt6aLUQPGHMVCnaZ3G/AF5SZrOz+EiFcrsJv48XezsaxSsIUeT/hgDxPCCPrSSDbFmpgO2N1Ed5BHwpIEX3Aho5eWZ6KLKHj+UrNYrwhQ2htZghArVZ5LQ5lo2HqUpk6U+eZigY0n9gH9IbILV7NwRpsDtVCy/xhbTLtb6mstZfnKwFLZ3OXINF8FRSKN7RRuv+x7jGdp3iBGHZa3XXYjUlYvJrfdaqe4tEztEVYGz6/opbGEar9dH4A7MbrBskVD9ccFNrG3WwE6V4eEY4MZ/pxx9qduk6ZzHSvlEYta+rhx9lX98LxjgBLbB4mFeOyV/55ADYo/oJ4hMYDd7T/puOHi9ntzPK1kz4n8gJ6LcgSFUf71DPJRBRBt3b5MurzdLdO9XnhFsPP2Vo+AFjWwxhXD6olD0E58V2PDFSVWt9JYl4fTKBxPJv+NsszHqGbqQ6VLVN8dXd/LG7oXCRbijvnv4nb8mOJxikI6x9B2kzK4+GSWnynKBEi/XHI5BC4UmPolKNdbvugX3169IXkiQp6lRcd45r+9Ykj5Ii8EfK+SJ/27GGR922oaNzdgQ/Oz/Gb9AWTCDTYBFWQ+G+z3Kwb9GtpQfeDjJ0tr7+BtK/hPCxxLpulg8MSvRLF0kGVpUnJZCkQP1szXPP063/vTxG
  template:
    metadata:
      name: ghcr-push-secret
      namespace: card-sniper-ci
    type: kubernetes.io/dockerconfigjson
