# ghcr push credentials for the buildah step (PAT scope: write:packages).
# Pull side is a separate, read-only secret in the card-sniper namespace.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-push-secret
  namespace: card-sniper-ci
spec:
  encryptedData:
    .dockerconfigjson: AgAhSlTszm7lrB1DmstMySxNnHlF/hOHJQ+3IU0xhh55zT59j4LTbAbZLkw2X6we3Iqlk8OZxAt1jyCwI6Bgd7egeKH6OFF87PF0LcxQJMSZnDneAXN3g08BQH+LPTPXz9CU074I+I7172B40sH99caNE/puKr8xihTERPooSFfvPW32zL+5fe66hG5IpVJgB8qa5CvrdNG4teZNbSYoFngds7YMYHrWuVwgsoVP+q2ZyYqf+ICEZazsewDtSxG7WXbk+kNG92Aq0GZd/leh0NYUqUyFh/7g144XhkkTYW6M8FUjv0RiUJTLtOzrKyX4Zys7KKRju2rnhDEplWhOLMMNhCYgyVxEv9XBQmgWwnscQCTx9tYfjNsDYjeMvcMw1EuphahYQz0HvM9OTQJzbqJdJXnm9YiW+pizCJYCjbJ4ESCO4sFrZ5wyeF+3wUuCtzH4l2y38j+xGvULp7tWGwZIBz6rI8kMYG9xewaoMd4OWAUeNZq0aueWUObhN+ybcWt10LANz7WSqOuEieUMP4yxod3htCqqpteUcmt1C5jpaATeoKM5n2JLN0haINpHHFfKpq2stclmFpyMy6osYW9Aj1ZehOwLOdIUdyLsrZ9cmJj2Le7xvjzPSU/PAJ480qwMlXtf2Z2qI2Cg5eMkGVPW129jiJdY0Xky2Ns+7YhauDruYPeVuOWVJsVt6zlWext+nQLbLvs9m6LG77083AVVx+PaaMGG/S/4NNatvRyTyxLzvyr2UYEwT3ljq2fKxg8DFZqpwunpRq3wVqaDZ4lxPG8znLXiV6ld9k0OfDHfvQk+2wI43q3FKowu+ZIUTg3CSpqN7BPTShA=
  template:
    metadata:
      name: ghcr-push-secret
      namespace: card-sniper-ci
    type: kubernetes.io/dockerconfigjson
