# card-sniper is a private repo — the clone step needs a token, not just the
# ghcr push credentials.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: card-sniper-ci
spec:
  encryptedData:
    token: AgBpIy6AAZd5Aqx1ZPjMcAvMBYQlInIseOQROFdjTRR8p5/TM4NZuArqcWnPUnkMUa6hCuzgVwtzdpsm4cH5c9zEzHvU1dhJ6F9Yu8YEAEc4C2UqY/6yNqDN+pl0hRc0SqopMJ3VEQ0s/V150CIGKdS61+08X+eSTdQEeqjj2CjFSYUmlEyZ5N7RoFLn/CxgUDfQW8xFPYP9uMG44NEsiQyc3FHl11hHRpHbTJI/em/PXW+xVKq7A23UoZ93LXSpqSSxrRpPxn8rENFMUzzmQNZMvvLn/h2nvv4WGn4HiQG6ek2O9R8B09Dn2qiOi3ZptbAn2hS2Bt5EWlScZenRgNRGPO/5NaVkt/y0EFOcyYIPwPBeb5QZbd+DX47/QpG3pjZV4ueFr8kObxuaobnn+bvK52muG3amIJHLyukoVIm+GdEmcyuycw8u1DWQqTjtdf6pC94ytqtOyKl1OnS4tXXETwNImNMoTKq/BohSibY3m3Nip/2G5f6LzaZ1XwxiKobEajjeCCRCne0RheSPftZxbW60juFvf+9zMikGD/hiTeiEwLFkcr8IvP9XXWJYD9sOVtByOe4rUTEhlm6f6KnU/ZGnXpBSXPI/B27/yDIp8OTrMnsb7etO+7Euq4hrrnXkCsqyX9oYhkRckuS1NeHjyos53wtNTXYoPZvzCgjAPqqdXZs9pjbsyxfwjahnYK7z2Cfuyw+IZKWoDykhgiMcwxDpWMExbUuf400maWnf+UUPWpzngyom
  template:
    metadata:
      name: github-token
      namespace: card-sniper-ci
