apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: headlamp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: headlamp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: headlamp
    namespace: headlamp
