apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: note-mark-data
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: note-mark
    app.kubernetes.io/part-of: note-mark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
