---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: note-mark-secrets
  namespace: note-mark
spec:
  encryptedData:
    jwt-secret: AgB8UpnoVJ4t9/8lp/SUsdH+4N9YSmu1WEBZuUuH6o3zwok1Wi3GVtS4t3RWyMwJh/QCxHT4tNVG9h9R0FnR8p6kJ5qSSuuqimwZ/FPyZ2B9PYLPdKEUhH/Fgzk+BNZJPVlgTrl5TFF6PdlLqbifk1RUYN+vFF/iLAUj11xNa2lAS8WLCyDi6Tl5hjUKTE3HmPA6Mhwh0QRMYqajghv2iHDvvXC57RdLtGokW6hd6t0Jlocmcvgfczvz41B1/V+kzBDraz0UmcnV1VXT00o0N5AQHHvJSwnu/aYFv9N2oUT6AZSWyCkQ21tJdc1Taztkrq1bBi0cv8JoClGJV9SSL1zlteUARXSzEecLtQ0FI4SVsmN/v/91B7Cab0zqEfD43EQH+KlFIcVpXoIbWKcvdQMWQSgnE0ye2w+pQjYw0RyzOjQGQmaM1U8zbJm7jMCpORFVUQR3EOO9QVwChmoFDp8gSQ08Mms4QdPh7ENjyVj8AC8I/n5tt29DGY+z3O5NGCmPz/PqA8E/OT7zKgHlVk8nIt/o5RK3yEcmRcUmSSw9GXR8dnSUJ19cKSmrQ55aW8ynumaWA2fvTR390ME2qoNBDhOq2ZV5qyjuSkFPvXDIogzUJx1SmD1SocuHjeA2el9deqeN2Ce1kqMTxHdmn+yjUS8aCtrMuk6v8qQ28juOmMTJz+fx7jnr8F3//ltJGbq+iiJ5+ws+M4SJywbmX6adZVR1sNHLdJ6bxSqfY4mDO2fWerwH604nJCmzKq4mcj9fohukzYNGT+eCcvTurfn6
  template:
    metadata:
      name: note-mark-secrets
      namespace: note-mark
