---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgBp/P83Gmw7+6vOGqINsi7dSEOn2MvzNSAR5iJYHFmDSJivLmdsnvdq6pRtVos0t2dz3fBbBSwzQlL6K/D4BRd8FNoZkk7ovCUOg5J/4iKXCeuhDdbQOsZMDYAUyFgZrh4U0CIfWxw1gEmPQ5Szj2dBkbCo/xsfgIILIFUMbuLdwcCi1c1aqaSYjiMNBhLx+lcPdwUK/C6KbMeckZkqwSY6np5Gl5tjP1xKIFlgDBQS09juW5tsX5oaTSwUsN6f/OpMkzhdtVFvAt6lCKvsU2rNQu1N44LjId+Te219nGgw0JPzXJas8QbQdal3z+MWCj+sPruWPnU0v9E/ZxavNVSfvQ82Z73TMe4FTke1o53ns0BURZCGj1hjUAtQuFhOxHW2b2Ekiu+1Ayj5n262IPg6Ku/DzQme65P5hyJZQesaHbvyOmI8jo/v6Rpv4UXxtwXEemGjy/joS6XaN/Y2StBAwibK+nz7pzdkmEckYom/XBwWK78F2Wu5lQlweYeNTTxINRNoK5W+cVzD5pPQBjw1UtY7etS8wBp1zk3BlSnh5GUUvS+UmE/D2WRS6a1Ps2//IxY34RnmkRr8kYRC8j6ptd8BW/azbtOusZ9rdhQyGfoczwIEhLymWNEPhta2YOrJRiGmRbus0dIzPe5LlohtZO8V5qaU0tJdq0jhIFwLxzStvDhHeyc/JUqBmsYfk8WsOiiPBxVZScfstWCJDRGgWi/asRH5mi2Rp4P0KXuetUu8aqr0F+XUhSY1FmUXwlRTDy9ifDccwD0IcLcNTrg5qXxNVudMJUuQaLgo0IHmr6UsAoIGwHhjU0U/uSebPK9TdRZvxS1gzSu1JS73iurCVHq4PJcb8KUYN1+GGuiOOYcvUSJw1Xh7maXbh/M2zKNxrXlmf+oHZdSAMCN3dLbEmVBBlQG8LR32HqS0QZ2bNrbHyFgGnS/6
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare
