---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgC2U8EJjX/+lcWP0UmLEpBZU/mac+D9n5k6/t00ZfdV5J2sqIx8Uu/4gMjO4oILMZYhabcVequ3bg+I/mAt4D7Fa0x9FWDmha19RFPAuOpGJpsZwAdL4rGmlccnTCOOZNkPGOR8l06w5vlkjTsqjlMA9HG2H33YH42XAAB3Z2l5VpkripsrcHf+mowIQIS/S7spL0R6OSyuUMGhY3l09yfmqgIwp6YG0LtCcEeMywXAmGAh5PgZg04zxh7uJnADu4lXBiINJzEfzvnXhuZUNG1sxzmd4Po67n+pSwl2Weu2H2Or3QBSvNpE1mezbNRknxgVHlrXg1FT3ZXwD99dCv1goqMmRHU73sccIfQ62WD6Jwr+9+wYO5fCxdpLegA/HR9hq9mw9Lhjpwu8EuiyWrWEnXMwxeSA7ddb5a2PAUpkv4Jg8lMmb9n1VYse33yDicxw+/WfbLU18RO+nw1OYA9RZ+QGHaabI2MObGGahJpzZws/kO7fD3Q+9su4isncc/pOpwy3m9yx0+mE8Lis5MtFnvKJmprmhQKFztY0lq5ruTo457xnbPhAPZH81jHy1QO3RMw+z9irFjKMbKzTKgRAGFO1P3rGsLzD4qnEn2IHI7xJT6gBDzQOITmzOmw5NwplvwJToaXaO2zYB8PcpdHuRrw+LD1couLsw+PNBQz6WcJsPvNXHOF1wxNgBtsT3K/EU71IOLOPaykoJUscx9EKpItV+PyoGlb9ElmP7/R9gC+MyHH22scrWpOhBa98uSCjLggHkjHwkGHJymAoR172gCMNE8K3mLjszSr7aZNxYuEeeZxmYBnxG0TbnUx3tDVp2D0RFyKaaKZr/3TcxpXfk53swCJCF+s1Krt9BDARdYOsK82qryNkDKD4F8LKHYYcblD4xO1B3FG30wtG3mrznYXad3j2wselhAqzTBWmvAervM97Nc/r
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare
