---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-api-key
  namespace: jellyfin
spec:
  encryptedData:
    api-key: AgBBWnraFILEe65/p685GvT6k66OeoOwDkURuJAr2evWcbvnLvQtX7o13t5i+bvY4oddCbkuj95EFSlYkNX418qsMk7zz2ZOUMmx2hAfj5d0eB/dp07L37HoMU1Cc4n4/yHH5YWosYfnyh2xLgQ8M/QVVMYztDUuSEJuUlkF3SzlJZYn1tzT7vG868yljH6YHVnpk8UWZRru8r9uMxOr8rU4letUfsiWeOrjoTdh/GppUcQdQ08XxRCtkMrMwSbpa28kpWvqpAhrHJWPaBTxlV2eSqHpoeHY/HZA6r41ubnDhMuCfwDNWV1c4tco1AcEKUCAs2Fp6Oo17QjJi8+6NVXs99gnKffSlKueSvGDwZ3lzDvGJtM09E/b6AZBfUHiLqvlegrRnL4FwHgIWF9OiHyrX0yFcPho7KWE7Xtam+4mts0ByJAj9dXS572qph1rxWYSwfimPQHK78yHskGQV9tanprjFhwq1cgYs0rLOGEDkp/yIfPCXiTUxaREzePD5IPUf6ZboNl9KgUgCxNICpgdvpIEZD71sTymR7WsQmcWAMKiBC12M6lUlitBCGCrKHVdqUPJIEinavXJdaLmWTvyhHm2RYHTuWJG9eR4CbDbeC+jSEP85t7m0+Zh+S66/0K2qihDf5ENjf/aL1iD94dzf4C1xPbfBflh9a7Eo7bXTaPSFHQlr62Q1yp3Bkk/omcCdQqhW7mO/1x5Au/tl97YHUo+hyqxuFGOn86uJJX9dA==
    user-id: AgAY6UB9C7THwBNDglosQlnqj75pMuSuhFMwuwIHZtDBDZBvfESWjT6VjwR1OBwSqbv/X7qJwasZLP1kGrs2UVdbDSa3Zemz+aEBQQlv8NpJ1R3X7/WQmWpobL7wAgurNEOEW/n8drI6MVe4+NOnL/cp1sNr9DHEsfZOqmSPW3modsy78BtVTOkPDQGbmD1wPmmg/MjpmfJDcSXcCJH6iDnGCnBvW8eYRqhd03qUxW35/RJ+/q8BaO1FBnWLZtpOqg9I8wIcQP66FrFWU72vOFwl61LxY9KNdrJ6mxB+JCgLE+WHQH69EckqjRnhYvT+hE9caujefZpEJZAM60c1NlKh0wg0/tBqDeCEXJYN6yzWhpASjC/tqLU4rLxYZGAyZWvmCvSHYTVe0McJYLtc1Z8saxalq2ju5JIive8PBGVRMcif3P3gUcRN4YHkRtGqj/3z0UPe6OMFoHUJfqhEReHSHTdA6ajojr8mc1GWwTCTRRXhLOfv/C45uehYZlfCGVfPaWWe0LkrS5nUhU84fN+mFwL9yxkBpj33k+j1Nu+4oXqXx3EEZR9wRkMqYgqdHqKGQymR65z3783tKPV86NL6aP5Nf0M8mO7TmOvu7GEuTYpYPQTmCMbI3Ja8KcJtUMEjqNliuLCwZhTBgZtbP7wIbahgTTBAak4gNf4sQ8OovE3OVinMayfI/dKmzctvkrNo/+qa3RBV6w8KmGa6c6CAp6qr5ShdCXmBWf/GsSAToA==
  template:
    metadata:
      name: jellyfin-api-key
      namespace: jellyfin
