apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
