apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-postgres
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-postgres
  template:
    metadata:
      labels:
        app: grafana-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: grafana-postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: grafana-postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-postgres-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-postgres
  namespace: monitoring
spec:
  selector:
    app: grafana-postgres
  ports:
  - port: 5432
    targetPort: 5432
