---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBJrkHRqtjHkF3c/h0tw6y87NYcAT/bAfQafTalQx2clzH0kCDxmjmY56rF86XVFiZuowBF6TDFZrnoaHPnQNGYIjfTOIRE/qSBT4i/cnQh2GswpA+oDY2ihk8L/3tRXRxxOxLdsXVJH+zL9AG52GeJmOA3rX5ybx5TKjhT6RSiItsq+tnAtcKdRiKN4gKD1EzoPQaQ6RmCEv3lyzzGvOGIq5LI3WJdD2mIwVvSnl64xqeRnfTKKLz+7DBOaxCswpCiJ0vuvADsxmYfZiRrVTI3lAg/Htd9WKsJ/RQOe+NkzKA8Un7E/gmZE1ZwUnPZ4MPSsjGamYR5MSve3q2H37ssQ3X8SXcU33BtCheTghTjBtm+Vs9Cp9K7KQ/e2aowZ1ocMLe6gy6JUM5llswzG9MqWElBeMmgQLlHzUR2B8tmhbeo3tG2gz4Q4UO7AcvLCUAVxcBL2MhMpLgo0HKRkijN3V7nYNUlNCR6OTzuLxWbPlaBUxp4Yyhem40p7n573zQGeTene/Z+wRDHZxvYPz7l1u9f+w9CsmBjwaWaHqjlcK+8gXzOnJy4TJmm4bVPNCJUebUOWzD2Y3tv9guCkClVQD52X6tvVOWFF9q3rur9x9Yg84+9e8V1TVBL59r/eKIzX/2qTizQ/wqHuWtfPaTRCK+fpvhxd80IWl64LxJ+SCjrYTbxwwPUUD/9xWYrs1QF4dVM6A==
    admin-user: AgC1FDw3laKdJLNdgKEfziVaefQlbBdJLItBgGtl6AqrdV4Nid81AX0ROGhIzucUjWRll9gR3gjE+vlrVraPokRPVfw1xsZrWs86nAzm/Oe2LkFovCOqVzglCbfoq7c2LDcvWuYPRp37joGVOLofP3u/dy0k2SAEBXpk/ldytgJPQhtz8FuH/Qj17TH01jt7WmP2gkMGa3p1jNm/0/8fr645++Ec3CasKaQ5bPWXigkVoBMa4w03+2qJ7WM8216Gkkn4dQj11HklgdTScDw2Ql8QLdo8PHGUvoE3yT+D8tUxkGG82vyvYSee2crQujm8lt31TIDmCA7OW1RIDMMw2itd0jQ5tJUyFQOBgWkxH4LK8VpcBay+20/2Yi5r+/fyG1OenZdZtd0L9CjcFJXoE2jBDBFi7XTCunUKsC6oy6nech4E3ZSII3y0WlCoPL0xADJh3bjPXojB2KEOLMKUy2X6ceLEmOWSPH1igWsPh5bbFSdgKC2F6tdD8MgFIBTgqWjDUnzWgSEpGh1bBTw+E/jqbT7tznmMzX+6rjGPpWBu5fa3YDz6XenYMUxY5Iu5z8Ji8Sx4rgfq7msRp4w+bVqIf/DVURfkw1FTT7ooinYrvUlpMloISYPa64LPh5aAkVyfKPn0X1LXiE6YmOcgc8OuhOOuAphDKDCDGLsYSfuXaRVcjv7ay5u1KqnZRuAL2qnPQ8ZoSw==
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
