apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bing-rewards-secrets
  namespace: bing-rewards
spec:
  encryptedData:
    ACCOUNT_1_EMAIL: AgCsgaP630hPmjFl9jqKrmAXpEXfBqOSWIeLpapils0B+hwHlByeCsdBG8QSBzgYpkaJYbMB8fsTcsp7DGuK0kCk9sNxTq0+RRVrSnY8LWR5wpR1dmHO4FRLC/elAfkY/0SU8cvd/yYJLCdNPKHjv9MiJv8h5gdffup3xIqyY640Ai/Jnu5p9pzzAetzpw/5P/DPW6oPaf5wuZQL09NRWDga98ipT2QpAf0zALyLF90n8ib9gF+ujES4jW9hTCpttAD3dPIca9k8mIuCX89r7CRl7+bzlmBpUG2+6gJW/4jlqwodR5uh92ga2h4/rMb7rtgWs7Qc7BuSR63idfqCPRWXlWi/GrKLr/iw5D/HurI4tP+dWCYTa8JeMAGnQIPdT2QfsJ/fpoJhsFPFFDE3jefgtPh0cEvPCeQZGIs6i0e86nsUlbFh0SMhjDY8z+K8xRmtPaeekjI0P8w8r59c3qsqtygUkoNCZZOyfMNLysfUVcembnU5NvmvK2zp3vjcDSoUbgwvhnTi6JZzhEHpVr3tEN3MzT9xsgHNHgeR7MTxeZ6+UzPSxmiUWJLLM48fUQCGm+KMMOhaicMk13gIR324Pj8Fyo5OmovoFDMD3YkC/6+2PN5LzMavvJeGH0gPmAWVyBV7OIq7ffE7+cdHY5AkJVTUXD2RoNH1mwrRD4/r1ynv13Hn7AVb8L5NFmUgYVWFhUFTQus/rKp4i6L3CkE5x9Ig4f4=
    ACCOUNT_1_PASSWORD: AgBV5pcJKRWvLvd/qTgntbxLw58VjnHoe1OIZWKp0HLy5QCsL2c/b21Oua6z8NY0UpUpUzbVBtZ+ehk3qIMBBM9U1H1EFtlt7ffDE/GNMRLbN437Y48zK62hfdkG5Z1KMX6onWfynxqcEIiPBNnk/uNouYhmJWI77L7cXjRFz7iYDBaq2m7n7E7df74I2B6Y1okmwukktcz4NeCmXjTMiA7jvE96KOmZwSW3Dp7hv1ZGB4R/iIcFlKM48ME5CgzzB/fE/uLOFGC9TRu3R9QpRL9lxiNkf5mLtynp3gxsTsVRppVUuCorYkEgXL61pr4YpKK25CA/A8OGCFerX1B7mAudfYVqi2uS1TYugJ0YJhQVPZcaG+jo828MJR1gS1EhpQUsvHbNN2Ky8xr5UDMzcoCVoDlGxPWdDG+cVTx2Upul7ORrCRLdErMksgQ1kY4bxFyTo+UvpJdOAQOSJyv7q4DHnFfC+yikSQnXmfWcRZdw6fBmRGa2+01yUcfiY1Ur6BOPLSs4uiyQoT3DCIdTc/fr3n/8l6vi4PxSFRdC4TIbcSaoVISEZ1xz5sK7wITl/3xZHcf/cHcJYEaWeEXV77kdms3EHu1FRkRZuboi+AG1wa6wkWWAwCTpf02PdM8iRwKJ9KvGWJpxgNrUg4/iweItZqM+z8V+5aHlkZdH6l0+Oj3Fr4WJ/E21KV8Tnn+2ph8/LbLzZqmHjulpW3wPX39tImLdeq9RcGsARVN1uJptVQ==
  template:
    metadata:
      name: bing-rewards-secrets
      namespace: bing-rewards
    type: Opaque
