apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
