apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/part-of: ntfy
data:
  server.yml: |
    base-url: https://ntfy.pj-home-lab.com
    auth-file: /var/lib/ntfy/user.db
    auth-default-access: deny-all
    behind-proxy: true
    enable-login: true
    enable-signup: false
