apiVersion: v1
kind: PersistentVolume
metadata:
  name: ntfy-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-ntfy
  nfs:
    server: 192.168.1.162
    path: /volume1/docker/ntfy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-ntfy
  resources:
    requests:
      storage: 5Gi
  volumeName: ntfy-nfs-pv
