---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: socks5-proxy
  namespace: flaresolverr
spec:
  encryptedData:
    PROXY_URL: AgAwHh8M+UgV6PmyoeRerOo9ZVFyBl5qsEmJ1k/QGJ59TiWx8CifHKPnBl9qkWMPm/JDJeLS+Z9pogZ0C/xFy2YmMJ4NU8lA4PgMUMhtB2IbeDzqXdgEylx9MlgU4Eq0k4rQANAoY1IQWHbKpkJGB1e5fhcTXCyxMApN4rl70whxg29m2crASC0Fa+f6qA4tnwkOEtuHcWCYUf3i3EBPE1taru5HmJE+Uj639sQLOjEWmp3iVnKlZPy0yDB/PD09PVPYADErm1PKk1mL8X24pz0IiMfOQoxkb86+1NTy6r61WW7Ak+VZPdNl9qSz6GteSkzudhSkNvCRtnbP/QjUs6rivW6ISBMcFW134EeAVRvIB4xK8O9fC54qDYV9oVYoH7Aoy4iPREx7H3snycMXlAiR7bPW1REYby+sOS8g5hh5NwfVjvuj1nPC+s4oYQpua4Dha7zD1Zx3/queW+JLL6nze02ztojmdpElmhxXmTciZkyo2v1eVkqZf4SjA2rj890KL0Xx0uIUQMN7GuQtVxn4JJqgZCjnzWgGiyxWNcg6BVJm5DgyIdGxWgRocPUAnM5bT4MGqKHDpKw4jNtZxUQTVpoo4c6I1KVuVODdL3anWTIN0XjjlQOGdKSW2HDwwjsPUzqBiEeTCAdC0qD63BVcooMVUaDierss3UyJDaqPuWLtB3TrDdX0qNROgiCnciUzUW4GNePPDI6kl7NFLs4xQFzLfOG9sjdWUNeay7XzTFxCmE/32CJIhcxVZR2Gc0MWojVOwKmfoJcnm5vozBO8eY7cM6mZoA==
  template:
    metadata:
      name: socks5-proxy
      namespace: flaresolverr
    type: Opaque
