apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: suggestarr
  labels:
    app.kubernetes.io/name: suggestarr
    app.kubernetes.io/part-of: suggestarr
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: suggestarr.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: suggestarr
                port:
                  number: 5000
