apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-config
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: recyclarr
    app.kubernetes.io/part-of: recyclarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
