---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recyclarr-api-keys
  namespace: recyclarr
spec:
  encryptedData:
    RADARR_API_KEY: AgBBfym7DPMK15PPYpJe56FkfByoi/G5eXnz9psUiuV8D99fQiZogEaAJLIXCJBwmR6RQCfbsnMdrUyIQcD/sRUhnmTTIPlNz8C8/E2/QtMQSmGbkhO1FAehVXoMmyHPrrzpXsOyybdtAqXs6IgWrMPomJ/Om8nUjSkeuPbJA2KXfe4Qkk7olmPuWvNnVQJniarKLVzzOt9gQFyAsRyuKNy1gCdFRjoOVdWJKVoyXLOQVRDUz65PFkZH7FA7Fl8jgPA736xQ2JyvkPrGSwVcnHVJVQBU8sB5VPLNW3RHPmsXLmw2OJfVSTN9bC6ExHSwJMCw9OOv/qxPoBKeXrwJ2R7J+LdsrcXF6POfnyXuZwhECsqdfW7feimWxQnhz4TfFajZ/nXcfROHlv0z+WOBpnFEKUC369eOW8Dy6oU+E7Vax9B/b2uzQEcmFOLzK6j55qH140i3d0863bxux0LC1abRhyaiP62l23wjot1N3w3BtCmpKPW7XTTobsXFXWMUsDaw6FhOKkbmpXWJI/5RShZb9GFQXHMM1R81SLfjgO12xIuBrRgISWQeJAjvhXz4VD1H4FkR8XtwkTjM8qXr0DusfLrmv3NuDX1wV/5UECnPpsYzirzjaP8DD57QtYTIq81PZkQq12OwOkuarK96QBu7p2UC2F6ryhq7vQbRLIVxnjVjNY4PzeJ/wecd4qoutrSCAqG0ZKnRXz/Itpr24Z9aJjM3ICfTAWAvL80ntlVNuw==
    SONARR_API_KEY: AgAE4GVRS+yvw+f3nDYzs8PyyYoJYAfpxKCnIuvAFQssc50PFjXkYzuywWhDkXoJxnnpwu1NQPniJVJd8u4LZZCpUPlF2t4wV8VvXXt4xSj8l5eGacwzzGzZF/BOwztUAVsKtb95f/3TDfmkhKXg7UDwqqXn3W1j9w6kTeDB1FGDI6xT+AO73w/KCdgg1Gi4AYMOUyp3+wrww1BksxvsoSTry59IoBPC2U5bDudFQvWA2Q1jE1a0qxKN3f5ZyZUg6TRCasQBlWOc43VnJxPcxU/KXGt0hSbEDodvQM4EKljyL3sBYc1sXwC+Rbeuq4hjREsAX1vNotrcYMesI0iwp7omtsUfgXgJsLFj2cPPW1B/XkeyPCoLwapAqmRKl45sAmPxy5KpWwNQWRD/UuGrHm6cRv/MURJTUX2qLE4iscUAdkZFXN8gyxohhjYOjGBcnRAo/Y+5QkyvlMz1m7VEzxhtfBY6snEq9B0t6NLrFfdlRIARYM8HJvxDhbdVb6fkehKElzs2SShMopl5xC3bf8++KHxW185xDw+asO3cRBoRRl0jOWY1Npswk4FRH/nbm6XTtF0WNHpn92hmKPROKMsYQZxxWUSLc6fTgJTBpTl5hCa987hl2U68ZcF8XScuJFL05KNIqu1Am8EdGeK/Cbm+AOsEJ38o6qpTFmXP4LoQh4XqtHiCtmefsdD5w/qDIy9w53m+L2tVdUD8uCTK9Dpzgs+qIo5Scl3iswN7xw1J/Q==
  template:
    metadata:
      name: recyclarr-api-keys
      namespace: recyclarr
    type: Opaque
