---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: torbox-api
  namespace: arr-stack
spec:
  encryptedData:
    api-key: AgCIb6YA6kva8PABMr5I1xcXEG/cU+fIV7eAwnZw/ub2o4QtaCwClqJBUzLvNHOzo0ItVk8kHDclE+gIzbAvXaQscy6v6vtvni11YvaHT4oC81jaTDzs3jqwug2pbEnF17gyR0wCaIHuSV3V7j8znuRyYCrGv7BGWnMIbFF9PX2QzpbXO1XlSjUN4dUzTS2Kw67qY8GevqGwF0avcMOsnSp8hZnK2XwpFCs76qFMz4xxQB1IcqL1+1mPr9OBfHXLA1d2bmfHWddAFgc2YehURSrG+hi6QWwP2gbV0GvCdwj+rfSMSpXM/dthU68B10Za1puxoICgFk3YRqmyNvQapF4EWP+y9AxVVlnkcX+opTfKO3w7SG7R98oTo7mBRF0yJ2voxq5p/hUKrRg2uCnaRDW4Es7i2WFc10N0e25205KtTXNNCTgEJ00i7Wcm/8cKFDI2RU7cHITvyGPfw1j4QI7ZGATCoLtb6PqctKzQRGIPbpOLwdzWrydkNqezsTUWzjN/2qS1WHPZm2FLD7EkTas1SV0A11Yu0t7wpYmBQA6lpANbJxtiA/EW00WEOntTJkJwo273gecuUrzvZRI52vE/WuJthX9DA83MIGDKRfX+PSku+gmQcVwBNiYlH7iWIsuZD70lakDNpknWj9Txxqt1pB17WqF9G9dIUOC1oSxPTK+XTZGefK/gSlcf3yglnuUYJ+abPc7Szhp5/H089Xo/dR8jPpXV3TGFP3PX0QN2v9ld35o=
  template:
    metadata:
      name: torbox-api
      namespace: arr-stack
