apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-nas-pv
  labels:
    app.kubernetes.io/part-of: arr-stack
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.1.162
    path: /volume1/docker/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: arr-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 500Gi
  volumeName: arr-nas-pv
