apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-config
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: arr-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-downloads
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: arr-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
