apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: arr-stack
spec:
  clusterIP: 10.43.176.86
  selector:
    app: arr-stack
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  clusterIP: 10.43.249.25
  selector:
    app: sonarr
  ports:
    - port: 8989
      targetPort: 8989
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  clusterIP: 10.43.196.90
  selector:
    app: radarr
  ports:
    - port: 7878
      targetPort: 7878
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: arr-stack
spec:
  clusterIP: 10.43.18.74
  selector:
    app: arr-stack
  ports:
    - port: 9696
      targetPort: 9696
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  labels:
    app: jellyseerr
spec:
  clusterIP: 10.43.54.5
  selector:
    app: jellyseerr
  ports:
    - port: 5055
      targetPort: 5055
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  labels:
    app: arr-stack
spec:
  clusterIP: 10.43.129.135
  selector:
    app: arr-stack
  ports:
    - port: 8191
      targetPort: 8191
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  labels:
    app: bazarr
spec:
  clusterIP: 10.43.139.57
  selector:
    app: bazarr
  ports:
    - port: 6767
      targetPort: 6767
      name: http
