apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          ports:
            - containerPort: 8989
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "Europe/Berlin"
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: sonarr
            - name: nas
              mountPath: /tv
              subPath: arr/Plex/TV
            - name: nas
              mountPath: /anime
              subPath: arr/Plex/Anime/Series
            - name: nas
              mountPath: /downloads
              subPath: arr-stack/downloads/torrents
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 4Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: arr-config-pvc
        - name: nas
          persistentVolumeClaim:
            claimName: arr-nas-pvc
