apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-data
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/part-of: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
