---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-secrets
  namespace: vikunja
spec:
  encryptedData:
    jwt-secret: AgCO8p/bOqzKyCd8TtgPDdb7ga4lxjYg/kdY+iNkmW+biTY1UlU/6uGSkzy0s3Chy5CA1SPYJWyfbeVVvQiD2udxJ0drQBWe13It69CYMswACB8RpfneslcL7/zZH1borMl/dOEX/qIKx+LRENWE8YoGRJhqW60oEIb9QvwLZZI10S/MYQyltyyTrWb1jbpZ9RuL2gdKbxcBXuj0Nh/PwzG+jyazFzHQaMRkWT+9rDFBhSOl1yfm74ymGKHDFL4dR58HIwkWk1I+O990iXo6XQyLTgZtJ6EClPufJch3IyFRd4WsITTeubVAD3PCkpvYlY7jVoSHaTQqRBAcvv5SI7HYS9MD9O7LcLNIz89X3gWSDWZ4sskt2fej5lA6D9hJ3Q7mjBkYq/IufmZ8dQO0aygsIykdV9JDx9/wVSWz3vKsRr2r/hGu4bo++MXSdM/O6/VPeXUo0nyJaIvkeLCWStVy+HQeszGmEy3b4ERsf0sayFSFxp6Z3znVENIbVkYT+NyT9Q0RBsTsuU1AsXg4Gb8i6CJdsEw5bA4EhGmXETNbJKgWvTlnmIzW46y61qZlDYcvQoWk7aaINNstYNTq4VQMSbMCbd/AHJPQPCNYqcVFiJ/enjySmB5hZqNLlkud9sJgWj9RDNM0ioi32jitftJeRi3hObG5hJoit8m0u0R1TTNy8tsJIH+9idGOxbK0l5fwBdteO2R9Ih9EGRQ0iuDcoOR0GOxtzonvbuzC0yuGTxc2cDgqglfQs4Aec5iSYuxx+4K7jcYtw9RX9Lz8RlbH
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: vikunja
        app.kubernetes.io/part-of: vikunja
      name: vikunja-secrets
      namespace: vikunja
    type: Opaque
