apiVersion: v1
kind: PersistentVolume
metadata:
  name: obsidian-livesync-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-obsidian
  nfs:
    server: 192.168.1.162
    path: /volume1/docker/obsidian-livesync
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-obsidian
  resources:
    requests:
      storage: 20Gi
  volumeName: obsidian-livesync-nfs-pv
