apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: couchdb-admin
  namespace: obsidian-livesync
spec:
  encryptedData:
    COUCHDB_PASSWORD: AgCyXMbPfPNn5Hkq6wIsgOu3qi85N8PhdgAS2/dN+z+Y7/Thfk9cChJCAIgUwTfvxo6bA/yLw2QpXOJE6IJ87vG9Wh1SUkPUwNX4wGjrK2HSxvQeE/m8HeyRJxGdQoE7N9KN5/6hqFzJorGeVeCQYlmzS/eLgulGII8etcUQndjtu4gd89sWq61yYYHBNIJgGb5XDdCjgkocQb2DegsURKooD/cqgPB5ZxK9X9QZjgVrUxvd9EwMOElZqtxPqyEroKtimPvQUoEXiHHmeenOAOecGeNr7gOu0SsNZIIsqMDHkpDClvrjfq3DEDklG11XkBROhwBh336Q3cjce0/SvILtkobYX+mUDlE2mRu5Y+DSGB4n0UWoEdEJqB6jPVhXyyfslnFvjjuOqvciy/gWuhOfh2hw/nksZ6236BHkl1uvzqdfadO1HVb+QgVExRS5BWBqyBvW+f8HZhk63YsVSEm3PWjnu5pnAcSIjo1fInLXVkoUpXE4lPDlDjEjiYGjCdQHksm1qaiLRPFcklIalnud/oVL9x1T+/sdMje9XFAUTzpYDXEdqKdCCAoMcWU8vSj76340jJJUZlzcTfuI/I1BC30Go09psxFLFxJYKN1N6/okaepHUFKK54fjGBNPDZwufGXWb61npKaeMoGs/oMD/Dyy4XeDMzdyvBCkOmrMlT+QKTHDnVK/S+YMonFWMCMCDGZUZM8IRiI/bwzHY1nR9p3RHrEpzDnOxJui
    COUCHDB_USER: AgCZ3nj6LMGHtSPF/RqLAXuSiT90uIKZc+6XMg5Df4s8ChTCponGQ2Se/ZchH/krQUUi8L9iiYyoI3S6LKD9vpOtU5YaLGXAetQzdJsT3+UmgzpQrdkQ/R2ziwonXBKf5f/MIWy1Cp/1upilvfWbDrzwNdlyBXVN6OPeb31UPVZ+bMSWHgFA/lGIY+nEC57J2H8IXf2OFqR2zfgzqGb5woT622DESm6t6R+wfeZt+Jy1RFeH6qzo+uigK5Sz+aVkL5UfFmZdeWN01G2hRtTiRcF/Z+b2XB/08ZzF0pXsuofpfiT8zwlXupZTDcaQIU6EfmYg60S/nzxCVL2tyXxSX3FEvEW4oWX5Arq0Ki4DLERITZDA2cjl1l/e18r5pgtxOVDsDI2vW1CRysouAmxjJmRbyzCw/V+/taGC4KOh0goDNmlHvWQRgI5OGEVVNjD5xmSM573Qop2tRVW38rXiWIV1DCkYObYbfRWiR9BFPgTWaUbIthI89y6PWKtePTFlJoX7QIPXSa+xMtRlYh2dSsloxBYZbENh8uxFwbh6FDgOG4QxJg+6r4T9OM9R3oO7v+DUZfnld18ii0VnUwBPRQwhNORwNPk9bbNjkCD3qisCXZauUtKCEfpymNyJr2VblhyFQWBYQPCVNPl7YyDvJ2Sf2tuAIgbdmSgu4WmTiVplmd/JQvfXZPplMrGfFdC5OuUryaVGfF5GxA==
  template:
    metadata:
      name: couchdb-admin
      namespace: obsidian-livesync
    type: Opaque
