apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: threadfin-config
  labels:
    app.kubernetes.io/name: threadfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
