apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whisper
    app.kubernetes.io/part-of: whisper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
