---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgBAVpxyBf/2Zf2TMqfBMwib+7sJzKfSZckl2F/krCoIVajkeq+Atz3IhJRS7N8aQYVwWYNrWqPIDlXnyXZXY7TGhySaM6gWaVHkCdlDfXTjZeeazt/GtJoj5lpf4XGoMrCn6NrRq9Oj0KQ6mTzsHdKQLxeyujMaMYV5PIYIgA1FjFsKbJLDUaeHAAr0FdEnPbR61c0vO+xji0Rtzu5CL5c4l1cYC6xfRRVEbOvQlvhaXYDoIJVl2hlyCH6XNCEnW+EbW7CqNa9oVdLc3Kb5lNdOh95n62GinRIJpgkWgzvK+FAZhOEACKrLgLqLhk+p1H3QaZezHDDWDn/IPQ2PBYp1gMZhNb1Qp6oezgJXWeYp702zREhPPq7g6vJc0MsVHcB5Bf03jEdMr1Mrh7tceMcnCzrdm7WLu/vrMC6QcRzWKp74GYWEP2OWB7+pa5uWKW7cVDCJpkLSUh5fGca7AT/hFKmSn03JGhIcS4zFbBrV5mmwVhkkt9KokTWMRFt3yLLnwgbp0JBgzDjErT+AeblokvX1ICq+XqlX9EVK7kSzrUU/xikxszlD43lKaHODrqfa0fDAPZVdq7cOR6ivejmMjnJnu69Ba4uPNYPYAxaHbsj2ISH4gxUK7csYGs6P2hYLCfs7eu4BGe5GMN4NVbXDia58rynnH78AdL7e00BbEM963KJ8jgtDs1f+A3rdZQxIomiM+bAp2ZI=
    DB_USERNAME: AgADtiVZmWXAVVg6OYuzZ1UM54Uf9RLmexXaxI4EIX+dDiyr9//XIGwopVlpI4vfifLSO3kE7JVwuwOWqdRDSfcsGWUcRys9og7YTD021xImKrrYC7DW0D76+5ChQRdLeR0FEswNDQ1vruznB1mDmcfXtacU4XgpNb9jKCUoLlOZsrKdJjS8gBtK2hKDRslEpptYKfIe2GWXSDRQjaaK/cVmhb1nyOOiZEhkCSLffLw4l2U+k/kS5o2Xs4fLXCVyKmfP6yi/0lsS3tVEf7R4Dq0tIGjpc1BOqHLi63I2sKc1eZXUwq80pv59ekIMttjaZq21cxh35P/agiqfXUXwz4GM7xkUaD9bvGZe4qGcVMGmEeCRN8nHnrFPNsPafFQd+NXgsUg2Y1OcuRStzel8L7enGioZcu/C2n5Z4APdn29XqUj5SO1RX+cVgPVdskg2LMmhpjbuGcJkOlYopngiyPY+BjGJN3Dq1tmVCndHdF9ceNDSIBan6QeyXnorwZbm6Tksz+88ZetTorJXp0gI1vU+T24HDwG4VhvAC+7UbvEKHc1yB9/p3Ucf2OIkyZiG6H7xjQLC8D3D8dgmBRplgSk/eJqwyYhGqv2oOGWjJsDNE1WpGUJJukHaE0raWjkZiiXcCNOhngGcWKRYhuS7xDo/psVqT5Xvv2QWxA1uiabJ4NTt1gLjYdu1ATjK1Aj5F329wWhKS2A=
  template:
    metadata:
      name: immich-secrets
      namespace: immich
