apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mealie
    app.kubernetes.io/part-of: mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
