apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/part-of: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
