apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-uptime-kuma
  nfs:
    server: 192.168.1.162
    path: /volume1/docker/uptime-kuma
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-uptime-kuma
  resources:
    requests:
      storage: 5Gi
  volumeName: uptime-kuma-nfs-pv
