apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ollama
    app.kubernetes.io/part-of: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
