---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  encryptedData:
    APP_KEY: AgCQEIWlPOnLE3z0FV3/GgAN8QhCfn9WCeTbEIKnP9KYUtQK0wpXv5cFHLl99X8DVEaAZFe/mmacEZW4o4iHrjlsTDOC/8JHEXTU9B1fHuy3ILVHvyKggaGVDXJMNZmZma/JbUCsrYQ02P5aGkheucu/IbyRvQ05KFOBlT7hEOhofg6TqMz7v2j3Z63W8MMQS7DRzp64h+4QMx1JtDl/lR+FD/sAB5fGPZDbpaRZn+oVJnBiRp9ha4FYc9dAThl8Bp3irKRc8uC8DjwnzXly9aLtcEOjg9jbi5R9CKvngGS5g941Z5cDBlKAgxzweu10Vicmr5XVtOx/EWKDdnao0sOaaqf2znQFH8L/5DPxVsJViyaCmt4ZI1bFXhzSTSDC0pImf17pJUqf6ngiVfuTsIFvOMtR/QIZuzRV47IEvzb2WgxltMewP17gBDEZj50HhsMORtfKAgblksKKWeSjQqdYkUwM1yaVmY6/gR5rxoOCIXGHN7twowlVLPhoktFbkfdm2JD1t6ROw2IpgHr+GPyfukd9Gi33lTKllBRuWHFld9qeXhviCcbcSXt8yY3kShZ8dHGAwBZTJ7NIAJp+Qkn5hkuUbXCdYvxf+t+ANFo3qBgQybSnmzJytdpehBb8seMIoCrc1knidOHAQB8mbnKjiLpUnDUpAr8evS3MiuEsENx0lZ6QsLrdOlWoe2UlS+T0ku0QUckVXckKJRXwKJNGYqIEV3W179rXDnrDBSAi6oa9714xNWKODSrEMUi9hQt++ps=
  template:
    metadata:
      name: speedtest-tracker
      namespace: speedtest-tracker
    type: Opaque
