apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    chart: immich
    targetRevision: "0.10.3"
    helm:
      valueFiles:
        - $values/apps/immich/values.yaml
  sources:
    - repoURL: https://immich-app.github.io/immich-charts
      chart: immich
      targetRevision: "0.10.3"
      helm:
        valueFiles:
          - $values/apps/immich/values.yaml
    - repoURL: https://github.com/Petar-Jorgic/cluster.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
