apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base.yaml
  - secrets.yaml
  - immich.yaml
  - monitoring.yaml
  - vikunja.yaml
  - jellyfin.yaml
  - it-tools.yaml
  - arr-stack.yaml
  - ollama.yaml
  - n8n.yaml
  - whisper.yaml
  - mealie.yaml
  - flaresolverr.yaml
  - card-sniper.yaml
  - adguard.yaml
  - trillium.yaml
  - miniflux.yaml
  - semaphore.yaml
  - uptime-kuma.yaml
  - homarr.yaml
  - audiobookshelf.yaml
  - paperless-ngx.yaml
  - loki.yaml

  - gotify.yaml
  - aniworld.yaml
  - bing-rewards.yaml
  - changedetection.yaml
  - headlamp.yaml
  - speedtest-tracker.yaml
  - recyclarr.yaml
  - reisenotiz.yaml
  - snacks.yaml
