apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trillium-local
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: trillium
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
