---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: joplin-env
  namespace: joplin
spec:
  encryptedData:
    WEBDAV_PASSWORD: AgCzkS32WlOeNNBruBAZv6xzX30VsdEbMG8voi8B5othvTDLT/B2gP3Ni177b1wWMpravkvLyMJST5MDJIr/SnLZGTwkVrxfbiSdbSQezDgWSrD6D3q2fqp3k83bAClgDHj5esWVUYTdlWC7UOxOg4S7cSKJNl6ZvwoK82mmGnm34HqRRdC4twANGPLm3v5XPkxBqBJN/uMfIt6ZdNcYz6Z+m1lTepGONnl3hpHJcFtcWEwPkjJZV1YXnWk9JXy0OkGb2NiwWIOUlEhazWrp0L7GgdhiTEPE+IwO7r25l0j10/w9xArUhah35VRZRgKw1Vp6YlpRjbig8QGlPLL6GFbBAm0i8L23tcKMEH5FJrRxMlcIVsWUcf8PD834+oU/Szcc4ehckLWfjDJig58gTYSgmNX8bqTvrmWSeaUNMgf/JEzQUefy+M8iX3yDg2xdDpy2o2TYfIdWLo/ARLZRrCa5siFe66G9GHDHJj6YCOFWh+iz6FrCgrYRjGl1Z8u50GLNrc70MbzR737JOzf2kf64o2gqTx/j6eElI/GXBFRG8jVC7hsVjk/U95xWDsnpt2e/uvfp7xSmz7ZEQOkNSiKv39+EK0tqgcJVqZamtvFS30R9OVUOVKbwfQv4D18jpabqwrL20yo/KR6/VI4T1CHHa3V2/oPFuzAd0fAsr3j8u6YCxdEynMQSM3SorBiLTaKWB8XLbAdvGisEwB/6uyh3a1o6yQ9t
  template:
    metadata:
      name: joplin-env
      namespace: joplin
    type: Opaque
