---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: card-sniper-gemini
  namespace: card-sniper
spec:
  encryptedData:
    GEMINI_API_KEY: AgB8yA+Q1HrkZ6ix6yQW8NS2geKmjs5Nmi8PIOsXw/lBk1xTwuOQpSUH/ZwU/rMXTP3HZbg3q3m1xDGiHgvyRay3B8cY8mlkU1nZb0lDNs4s1O8Ln949nGYAT8hx8FL+gJII3/pdpVpc5pNc5p+XDeaYtHEauTgc54OBD/DhmFpUCVhH9W0Wg1ROlBur2EO/N3ie9F0wwGiX7NRbuLgijbRwSEfAi6m7PoPNXLR4HjgYeZ79hhtSyhagbylz2laMghMSQu0XHfWkrY5PJEVR7SIO0jsAie0DNgPSW9SsCIfV4bTsyCFHKkB+VxvstOizWhzBFBp6nShz7teg8jKbLbymsgTWe89t98fkr+tH6v1g/JdQP94r6GMM3t2Klx4yyB2xVjJ+hciNs6IkEtDIl5KtlLSSx51O2sKLsg6qWGRwxUW5OPCGRdM1dletAyl+Rz8PrDacN75dVtvOP3kgiFkYJoERxkMucqN9KnGdAcIsgR2fpnYuiGCQram+BFNwkIP+LmDm+e6MyBnO/w2WUzH2S7Pmp2DRRypb8O4al8IfFDcekV69YNPtZhWqZC/dA6wo0i0HmzNEXX8+SI4pY6aDZAMMNKkiYT/msZd/PUWhpN51T3laXjyQgEzZ30EgYOtvBbXB25gl+uyRXXcxAObI78eAuJtgYx3ltHEo3k36TnbK+240F+rL9ciIar4ZWeUh7rdSOOdukpxsvR5UfR63lSnfUpyXk/yd9I6q1u7T3LgnQj3p3XFxJSniRKLtH8YYb2VkOg==
  template:
    metadata:
      creationTimestamp: null
      name: card-sniper-gemini
      namespace: card-sniper
