---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: card-sniper
spec:
  encryptedData:
    .dockerconfigjson: AgAeK2nSHaVE6u65Hwh3SttgLGF9/Hnzi9r0CLnZmPDwrW1Qr1nooAnrTGZErxPVKk75rEJANDpxle5nEOIvu2piEBkQjLqVguWxR6AK90KFnDLGcNtFQ9ZgaZdiTqPPcX/yfTuUfEOPWXnVmED9S+YitglyrpykmqS45X7956zZ+YyZbZ8r/sTdZQ7xnlgm7FMv8/BI4uFogcVbWO8KfmDh83/fBW3PfPxy89majx13Ic4dg/s95O7YcxCJGk380TDjBTE6N54Mtke1BA/jGEmnTLV0RrjDFyODbCjfjv2/Hagh56y3uMPF8ZzYQ8c813OhSgIgkvpwqtaHAbotObUYjpkX0ygsfJBhuBJ/zmLIuebVw/aP7GKoJDw+DMdPjXzeA/RVaSt6fBdhC8B19JiiaZ38apDa/zjAqDNGzyPAxaK9RPkKkJEtzDZQQ+EzQhjpVLtQxMF4yyH4/vxIjScfhIxLUWdjuBchzqxXaDZQEqm5iDmCawjs+a+ItxV1U2rLx9fJm0HJ8hfFoMaL8YKAe0QEsI/QcrAnrB6kqnfYcmupyc0gdaLN0NqZa/tio51o1zX2Q0ZsYddg11ZYNAOG2tj6wTka4rHylM3EJt3pJRcWEvExVJIHCnWGYwAcS2fgHoJEu8lEH/RGLSQJtfRyg094AgSWsNbWm0/MsWcr0vCRFqQWr0U2+Zzfs7J2t+8ehpLGJWykxfpMRT1vvSPRqEZi8jOyp+pD208bfCrC3Dc1htFiOkTCGctZFgMQiCPgFFbvQ/Ys6lpu4Eqz0Py5T2tqsGzszvjt7Vcqc1jnJZDKwSeik9sYhX0gGzVbKpL/DZCDG+ij+57Svxnq107Qklri/HgzkgYUQkpQ/EDxnEloK8QF46dSh5mIprgm8YdE/NZ0BOk20t4pC3t+9EYmXEesAHXqAP/DGur/czFnF7EZSF2Rz6Disg==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: card-sniper
    type: kubernetes.io/dockerconfigjson
