---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: card-sniper
spec:
  encryptedData:
    .dockerconfigjson: AgA07l6QK3EplzDpHBp8Xjn6QiknSdkEUNkB6o1/uhcQ3e5GnI3qnoh5vSmNonmBJCjiOkT9x74aPerB5rb8qADQVid/GJBOwRjttJ3+i59dx4LG/wb+qGIUUY3sJE/TH90ijD0Cp/8aeDQkhLHZ3Q/1KYbhXajGesseNjSJcym19uv3TGMIYqYARcVX+C/ScMlqdvcsIVdKsrpL7GNfH06llt4woQ8DY2v7Q19zh+wAj59WQHh89er7cx2WdUokQ1fHyVSSMWvULuWnmmcSUKfl0yN590KjXfuuzobla3GCII7Dx4o22/i3nxs6Aqi4W+82Q2DVDw9m5ihtGAUEEGj0L41CI6L8WeckjQRuCEXq2HEv7Sz9VVg8egMjEBya0TsDjCwQtL6iFYIRlyWZa8n4tr9wdTyhGRxYC5GcfGlvNlsg2AExHWQ+nI5PuLoRApgIvbLJJhSQdL1MaNgwRLQIv6ui/LGVbHnIGhRIrgRJT8Va3gf2zwFNq0ibmalA5mbjNWtrWazi0KAAECgFaFq8e1xXsJ/0VsCr6ZPfMyot8H55jRrGdZNSgL48hs2rijB7N9ujUScBaUfIjP2Ve3zCcNs+MKHz0TrB0G7JoXf4rruStcopZ0swHiyESFmycKFMw6vCE6996UoEBJsl00s0ERBBG1GrljEVQ5rp8fWjUWFvGQmb4xpEOuLxugELFw/JS1C+TFH0fFDO17JTHjlRgaKm2T9UZGL6fQP0IICI033PesfgqB31kaN88bNGNXitbIwl/4wrfe7YPTdu3P2Q0inPMO8EjN5SWy/+Resh+XCgwgii7UcGdeQlm8r7OZMyW5UhTAlalB6lHel+tjKxwYRCfYoDb1fg0341YJkaw28xTArofDNyGWJBipaiL0e5SHsv7Ss+pZfjf91aFF0eqEAkjv8lJd98Ss/GoqkzZU4h0UQPAOhBMA==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: card-sniper
    type: kubernetes.io/dockerconfigjson
