apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: card-sniper-iap
  namespace: card-sniper
spec:
  encryptedData:
    REVENUECAT_WEBHOOK_TOKEN: AgCO0utjdO1ueVXfBqKZY8tetNvc5NfFDZfZV8QosMlsb6U5hkKHmn0ZctRY4x9vy5cyZ9yCmbq9D+TEcV2P3O2EF25nWlngOBycoGBTKZnUfQGssJWvSfiCLaiI42Lm360u9A2UoKd03AgkzBxx6vonMn0/hXBPSB7+Gfg5y9KJ0LCiTJ/TYPzXJjQetUMS915ja1zfpApyDgzcVjNqtTmDwRWBPQ5FRusRLZEBqmeH4lBp0idKHvd10wNObTftYM8aQTTZ4Yd9Ho1bZfSz6uFzo1ckJEFfFs7ikXRGszBPTOFDPV7eAHPz9s8PER9aAa6NErhh6wFsD9uNcEF2Z68YG2ZjyTOv58zyZV0oNqNEMCtnCweFzt95ByAmO+aXSAG+JrY+10IaAjIRcY4aae1LofXM4TWE0r2ENUWtPBRDYgGH/XsniqmtE/ZvQmOFRUPp0WQwNZWEVzZKFzCC+1+POc9FMpF8A9MS+ZzFzUr+kDu5cMRFgzc/qeGgI1mGnilo40+/dIJ6ec8PwIUU3RDaN13OHJtH2lqJTKSxnzwZs4ZLPz9w0dgyPfrGSvLgCWEPEC1Kqv3nfhlVCNjxHC3MYNqsUenfseTu4NcPLfkTOwAqcVyYeSA76qz0T2rQq5F6KEW/ECGGfMnPBaCIp0d+fwYGCTiTuALPM67YoEgTWtNkVlK0ksBpq/IFDiQl/Kia2DMv6r0nHiC0aLvwwLXOYloalkb7xtYRSDfC1n1GddB5p5AZFkvM++sDpbmGsnQ=
  template:
    metadata:
      name: card-sniper-iap
      namespace: card-sniper
    type: Opaque
