apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: card-sniper-litestream
  namespace: card-sniper
spec:
  encryptedData:
    LITESTREAM_ACCESS_KEY_ID: AgCmZE+d1Nc38yEAVbG1XB8CftXfoKlEhmq0g9TBvdvQpZcGebAWXrpBb7g3cl/viNH8rnDNwtHlgl7Zwhr1GO7p/EpgwFPl4urI2wJKfhrmb1vIvtO8lT70JvfHvXG8FfWhhjCDZd0uQsJ/gl6DFVG+yMdVXS25+XKmiYxBjddLf/hR3McVjaIY/D0TwjazWTLVssxD6vFqiKPjII13U+NcairgNa+IJPp3KxXazvO6IQdpUhQ7GaIrMtFZOHHjl20LtaAmHWJbpdSR6pdUbansE3iy2Zxmlqrukbtpu7LQzPCjl9DGE6nyNAZePl0j/z8w80XaO0W6wen5MDRFB154kA7ejExoRLp79smEtVN90ER77ZxKS/LQOtxY0sm6pQKt9YRe2UYaPjcymvk7z1ViDktC4st4EAEJcSvLBIFzacmgCxjgE7S5MfNzAtRCJXqJA86OFLnMUCwif/InkU7vp00nJPMrRf69AokHIV+rGYMJKLZhtVtY3vHANTFVMumgXAyPXUdOVGCoH6Pt7Kh8tt1jeBLIO4wlgBrJJKR2qy6l3mYYcqoTrx27urfcaxHjlEC+rmGCHyVO8vm8R+Hc0dptO8FcFEG/jAowUcfuABdIjimINL2AWjKrvnmYFILv+Pp7V2eBViJ2iRp5Eq7b2svKnN4aOoFSZt5EcInoJLDU/Dd2iwrgjasRvmMGssCPmQULuoMzSjdE
    LITESTREAM_SECRET_ACCESS_KEY: AgAS8ZdZ4k1SPKdAwNlR0vBztV3S2APKjkfDiEud0XFhqNyDi7MmyKcLH1mWxug1qlanFnVUwdUXqk6guqMnxOrMCI5/AZSGEKDCEeMXLXZ9NOyqN7DIK1qOirO0mRWMaTzSgi6cxYNXEjX4nZw+z7cfUnoiY+NUpW/9jLqPcF9ujTZOUWABbEFrdnCwyqBb2gFDNoSZm408t5xaUtoTRs0rxpQfUGXTDfo37g5UUcu4w9YMPKVSJK3EYqpqEPHMAYepUsTVG0nUKiAlyBD4+i0XdlegXt10ZDAZmSRYsFJ/Z5/IY7G0u5RKze5P+qu3djQq/UZ5h1OZbFTvJcW/sS08P2XaoCQd/YuY5GB/qF/YtvTkVZg+JsYobMG23E5vSSX5/rNNYf5wzn6jZ6j0dwQ4Dl0SVQZt3YnJABAj0c3ZzJi2ZnEjCNv2dpGEzF79AtHZCUkSY47zNtkyUX1XIJNzTBqQeQK2upYCNcSt69fL52f6JMm6guDTdpI48kOuyoc1LJeStAazsPZqJU+2vw9A3EdSu1PwQOVC8SROvXWWOG3hgCAULm2ztOgto5r7hsqL1QCrvFxHV4zdkpsRVVl5qcC+prnOH7i6k8oosM/VNMzuHWKcaXYBC3DA3YH75aSfJksW0fqYBpXdGIWayS9Si+Q/mSJ9Cn3F7frs56LwzHlUS1t0N9wC4OwlFw3NO0HTHeir/wB+T23uu7FqJN9ylsiFGuxckW0IovGZ5E4=
  template:
    metadata:
      name: card-sniper-litestream
      namespace: card-sniper
    type: Opaque
