---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: card-sniper-rapidapi
  namespace: card-sniper
spec:
  encryptedData:
    RAPIDAPI_KEY: AgAtEq0wqWIOfk0cPtdzcctmnXEd6RMIAdmayP3qDC55JAPaoHar9veTt/9ufPc1bcG2kHkrBlFEr3b545iiMhHS6yBG16bD6EToxaR8RHDdiW/LVCXT31uGtEVbbk2dg00GBdIs8HzUlc8aUaxBJx3Gkmghzy2dycCFg5qpgcEXvqbv/+4Rd14dQtksAc59VhlC3aYIXjOAkiDCMbWjgkEH+LOTnoFMcxJIArC0h5he3T2Bv4RTecljiYYKO3W0FxOXn/mjGo8oes169DJeEZtgLHIEqBZmprqpy6ltz95cIemcBcNtDwk4gZ39M3AaggCbMdsB73q8qSlyNioCVb2g6fWjVpOUXZNidjJ4/u5vF+1JrlfS91gvBk5QLq/cnXM3cO3F1/R/kBUGbXxzZa7r2cbvnRenCWevupnk8CZtW3GVYhuIpNCYwh3C01hHs0Ce5c4FyLXBd2Iokd9cZye+rQyYCyRcDqBetm37WD6S7lM+Zw7LkXQ/2my92kM3dtzGvk6ie3zcdNHT4JFE2ONGMzIfl1vGLDMTQ8IMyWK8hOkJIz+OvjtKe844A5jzpLr5pjhHSSt7wPwc6Sa9Gvb+fy8KiyUFY4YKnILk3wDC+dDzAPesKL9IeFWRKo7AvgNofxxlVk+hU88YHZXTFYovT5B0fTMlXuTSagH+WynrTLaU6Ahndfod8tOV055o6Cjv95eMKToW71fuUyXUWm91/pd9nIIpJHi7SZh/RzXSQIg+Xz41CCp/CLBi9JP13n8QyQ==
    RESELLER_DELAY_MS: AgA5Wljsk57CSe40piYjOgFM/MvwctXjQZgmd2jk0zpaDUXTqxxUA4NZrQIXG7g8XIDma/5XkPw0qmiCagu045qxHDnFFdZxjtehWMQLtRWP0PHFRocuYeidd4XTdHoVOLEn1jnUq5NMXD+g1c0sYb4GCMfTBhv4kLehdb/5JTBH0fbMXDtvaiHOnrCl5d+l3qFONIAPhdcaPpIjN2EA5VZu4xDiZ7wkyollW53SxnldLQQaOxjdVo3iyEZ5b9YoQ2KVePmdj8HQvB5Gve4opzieCIUsa0XwUVRz0BuN/4yH46s+uYllzPhvJTGZ+Sva8tD5+5TD63Ki2f0AbkifumsI84d+H576rocRfcklVLHlg5/f7bNGDN6go7rz7gRaZ7Jpk+n/W6hqIopyiqg6hGPdEdMyneoAM6gwS8QM3TWm6UWm37uHcCjl1z/+pVY3TwIbCzAReEyQK3G8bZgq0/CsRNOEEzJn0wl1a7MSuEUNKyIeOdSHixdB3sJ24ud/SQK9YnB7AgpMjmi/9KKEkQ5BEhw2QlysYXK2fnf+Iv0Bxo+40lurJSBubP1jJwZrPQi5JSBeOLFikV9Xn+gSia9XdD4DL67z4a3RyjtoG9mrAuwRALOvVKzHbCJPbEtdYcbCnrhfoFGEv1F4PNtJUD98hgD6cfnJ7cZErdtXy2bQvODVEZoCXEHy88X7IShSGMTgqaxg
  template:
    metadata:
      creationTimestamp: null
      name: card-sniper-rapidapi
      namespace: card-sniper
