apiVersion: v1
kind: Service
metadata:
  name: card-sniper
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: card-sniper
    app.kubernetes.io/part-of: card-sniper
spec:
  type: ClusterIP
  clusterIP: 10.43.100.77
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
