apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCS4FzfY/fq5+pT3WPXTIeALJ+GBLy35Bm6/tcuGtJwrGteDUS3SFkpqxwtkH97MJWOKVUaPBSO3Qn/FjhLavWPJETfdHqYgn8naRoU4m+feHA94NhCt8R8RmtNA7fBFXdZ46sd8QugCBqnKeWWiMOrG//VbXd61OrnWnrW/9mcUvb3/YPXhajvMwvUiO+wTkpLYNp1lC2DPkxb+UtMbScBDVE0ENxEohhHx2fH+pzxan0+OYixsuEZAHqR+2DzAu0JUdi6VZJMguRyeacZMHF3wkIZMpRpt0n7pdNjYEPioFyaVbkGgOB+2Um1ul3O99FX9b9Xvytag64sbFWg56FoZbQOeuHh3YNiSdzTOa2ukWrDCKp2opFpe0LIG0uPvjIf/6KAMS6bjBKYV6/StR6f8O0aB4qhHI9ApM1UWdzx2mfVcUv5SQaEmZcjjXmfuBk5ym8i+WMoANOcrBBIOjgswaXXBMgUPZ2f3CGtkxn7HI1gA48nRo50dk1EFwHM2P5U357NB5E3ptej+nGayBKe+GqhVl8CipLBDHNCJ5aG/D7UGl+uNkZgvUhnoJyJaJFW0pRkUijuQZDUXkyzHGtE0yYV5nAxnQg205EzjhdRb1witHKXM1ElhkT/fSUzjdeBS3YVv7g2aVkFY2z3PaOk07nD5psR2lmnBYvwzqNm6l4wWOXgsC7VwSVUI6NPni+k4PfNAo5OR8iUBRq1q99BYSkPLPkiNHhWHc2tkCgn
    MINIO_ROOT_USER: AgCsZbxacWXMLt3y5UASLmgVKQTiP0WBhMpwMxhbTD8Dj7np5Cdm3K3dbblnQdLfyVaTEKMznPuF8Wn+3vKstvYQshJmAhwerV1glbf3UfhHBnn7XAnWVHfPSmd9RGDiZgVbu2rXU4phGZmG9j8mTr19DBtxWWVXXEK+v/gspPvzp+Zw1eV2ThVkuRnnUu28t+Cscaou0/O6eLhjY6Oo2MHNtVc52jUqscDUXjJOhDB+2ckO9cdhhZkWvcJpjzL/1gE7yl0FgfKCbOiZtipAZHL7y0eCtFEYG82Gx5ksVlKmxjyuWuGzSi0uMTRCBhNpsY7Q46JKHsHlniveJrUFgNqpIzEiVA+dcMjXiwZ4j54qqamWtwrayMTg9Ns3GYukP8gszhIwr9acVzYiAn4gRk49kI7a6ZKboMgC8NmcRHW6SKv+qjO/O2GXvqC9lPJm9oCsdmUMP8w7RDIWV3mrGPJWef1TRs9tXfeSjaZEIfS8IfwEXDDt4EhVHtZFqsZGbp9qyFon4L+LAciXgew7V6ckM4RLs7MDNAofnUGX141jiGF6JUBJetTcKw6at3XOUl0XWWxH7c5gAOpkcZngJBH2zLpOee67Me/jbJSiKnwn21ooH7HN7EWELT9x9fiS7RWkkUM5ZDJaQ/tQPLkoddjMDNAgtSAZNHeDKRyWkqUdyJcM/GtYny40O2jIoHX5kw8P3+w/97AybWuFmkZ1lL8=
  template:
    metadata:
      name: minio-root
      namespace: minio
    type: Opaque
