apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix
resources:
  - sealedsecret-postgres.yaml
  - sealedsecret-synapse.yaml
  - sealedsecret-mautrix.yaml
  - postgres.yaml
  - synapse.yaml
  - mautrix-whatsapp.yaml
  - element.yaml
  - ingress.yaml
