---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-postgres
  namespace: matrix
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAvhniPSrTgCooGYCfcHNQdBtOGhCa+EskNLi/qjp6oNlQ9L6PqTPX/56ptu/JRd9rBXe1lz4v5GfDomWOEaembiS1UzoTEZ9eSEeCNkToDworZ4DHPclIosRBSrwG06I4Jt5LvLtqSBbjG4gByiEzhWxnUNdXDYk+HXGkztp+Iy86RBYstsedxewBRNUS6aMbkbKYIxyD42tItUE2wlUKPhqLwmrRrijrbOHkgjizbzGePcUJrdwlwU3utUCqbYS486sC+WAkUsZL4T1148Hc51TDraEzJNhO6y/NOnZPHJTgO+tMjP8jEoENE2FlceIZa/ummBmv+1hDkNFHKPb5PP35BXK4L1zZCS4FwfZ2vHsJwpf9kiHScqobC8gRBh3wHx7TBJmOmPVNJg+6tBqYVJ6lLSpsLU3syqCaX6Iq/MZDP8f4vCYeKjNSuC6012rfpGVdJGJlNZZB5DpCUlBt1zyaGDsUW0tScdKnbSzzxpA9ZLc4iE7tbkV9LC2sfGpc2ZQD5wzh8mWuJTdcI5F8RQTKGXIl9L36LeGfJIVqm0nUPOmlXq5CjH/g6e+Alp8dHQrBZ5KqA/fKSLblj2PkuGmsAVk3v/ALATKsiSiim3/6yHyFjB7FSF4zNvr40CaZ+B1GO2FUKB8ZhPwvj1fkHHUW2dEGfJ6HZZ7Pcc/mBDh0ebGtgqBYBS6pQsIzyYFYFAC7q2Rs5W45CglsHT5yagJP4+ZOFDGHQAXMOPohW6D8gpij5M3ZmrVa6Iuaasqw=
  template:
    metadata:
      name: matrix-postgres
      namespace: matrix
