---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meridian-claude-creds
  namespace: meridian
spec:
  encryptedData:
    .credentials.json: AgAQqPO9UVXoUf2RoicjpH2paK2MgR67XZyrb7ImOq7f06waIBD/KLHP0z4oGnuoeEQZPmhmyx7HiyGu+XnvejIM4Ja3dJeWd4f0ouIuP7G3rGwmOAVk1x1KrVzeKf5JszanSOLKLXrqjc025nwnbGt5aCMFOOoKDAGs83K8lg5PH1+qcsEKZFrsJCuUOsw2GQ6etcqCHy8rfd0UjqW0V6Y9XOVQpoapE7nXp66kzDAyeBuGdct6rfoT0KidOs8DI5wKnQpbBgfGmnsQqBmfG1UoYC2ql/ajECk8w4rQtNvosjLgH0IeDYuPocZtJsoG1uErGZ00OnpGYEpNGqQ/C7NtsTsDYd4GBWGus8LL0wCGacPZsUxHhyRt18y5mqxhuqVrPyZ4AFsiadc6I6w8e6p6U/8ocB9RPJCOApEy3RN3fNChSTBaUoZr+X37gpKKNNvtnXE2IXdpUQAINpfyi4f5dEw1PdbXH+l0symjgVCHOKOG+KoUO+HozMWK3olVuV5++EsynycdIf2/Co2KWVbnaepRqFyUvq8Fg+o89yglWQTVvlpqdaYZxX1Fme2DA0O7EHf1VAc18U06gIxEP74eeF+PTEGNipyFj1kWSYJ2k6j/Pit2eSyZGPZvdcdnnlO0NTd+Mx1efeppEY7eEon2IFGSLfk+At16VesVR9TqqwfqjDquJ/H5GDqHZKB6EwDUHcKYvU9B8pM5bHkWEjJjKj5Wtwdya0k31mrUeatezXNTy+0vPdqq8LI05uQWV1zT6zd0KzAWU6YwMpf0CVmsdMZxHFROo1kcXiVZZc6hWRuSJYAExceptZ6UFGYaYVDPdLwk3E/4EkzIlIwe/UKhyOjMRSGm/aboj1vrZqnWbD+QFBFfhTGhSzEvklFLg12iLpHLFaWJiUDx+5izX1177JA9larGbS1pA3RHKqzjo3gemGdWB/OYgTwYiTjETRtaMyfSrvLS6Xr5k3TWWgQ0Z5HjS8qF/D73+ZBVMBUfey3NgHjFpVCEmFJBqhmzNcrMFZiGu9egJp7ZKs8vSA6FLkHw00bP3KL/M2Y1ofFyXwAbfH81zXw4u8qCMg64VLIurmXHPXT/397sENIh1oC5L+fS+HX5y8czAxhfhMaR2JOURpAEqYXCpUQx5DVDLR++2I8F9dUO5kAIKWE7svcxyj0QWoTk+iGr6xi/6eALfIwLStBB+chpmTPLrblvRdjWmSUtSZ3Sujp/YmjhyPnlx9YvfYOlDlazbLuictH9PZ9YhuQmrD/7NTixN3a5N5ToH/qONsasJ1GmuidMO+tRb49MT5MDCAnU+5Vb2ONVmBcH7gPcgg==
  template:
    metadata:
      name: meridian-claude-creds
      namespace: meridian
