apiVersion: v1
kind: PersistentVolume
metadata:
  name: semaphore-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-semaphore
  nfs:
    server: 192.168.1.162
    path: /volume1/docker/semaphore
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-semaphore
  resources:
    requests:
      storage: 5Gi
  volumeName: semaphore-nfs-pv
