apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-paperless
  nfs:
    server: 192.168.1.162
    path: /volume1/docker/paperless-ngx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-paperless
  resources:
    requests:
      storage: 50Gi
  volumeName: paperless-nfs-pv
