apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cluster-cleanup-gotify
  namespace: cluster-cleanup
spec:
  encryptedData:
    GOTIFY_TOKEN: AgBweBh2K9AFKvIGatFuy74LTupKS+qj8IIFhpIYNgvjy2J7wuCqeD5sWd6pvd0QUHnfSw2wJKyzlSMegNOvQxPmvhulEIMUzpFmLLHzyL+3ThZqAKnKvO5w1JoQSquXOBfxylhxW+kjW7WgYglJGNE0pOMSnztHgGpLvI020h06i9942XVlAqMhjM/N2OhL4WW1S6oxCJ3LV60k/9Z+sKFQ34ZyQlIiryggWEG/+BzXtaxewd4VSNSfdFlzF3ISLlB+2S5k7gNpwZ8PwG/LDbyfkL9yLmpIL1fDd/2Q8cS52KxX69Hv69TqIpTvgB4ON6fp59C/QRy/tbnlCB5xFjVCRNzOanG+B2pj2mLTz8/UaHvnGavOLQdP2vzRYbgZo47Wlxfx6KMqb6D8ppBBYXxrO6IdVlmQGwVLir4iMstcPcOitpydJa2ylc1fRt3QidPnNTx8MUQuZEy4sPWZxYuEFGcslqQ71C4vERo5ZDuycnLsNXb6ndt0qHygxREmW0ihN73h5BZMs+7ScxX9k5QiHwvKxctnJEtTPN+fSvEf6koWHfkwLk4Nbvh8+SjPyI3F50zkhusp26oZ43UEOfXkb9W2ZD4rf2GIBTT3+1794I0wXvy3pxsaTxr8OlXcNzQ8BNvADfQpJ2L6hejKvvFRmLo9W53ST1N5OEP08kKaMzUSVZzIIQJ1JKWf7TSE/xYcSz/80V+B8THCWEx1/ms=
  template:
    metadata:
      name: cluster-cleanup-gotify
      namespace: cluster-cleanup
    type: Opaque
