apiVersion: v1
kind: PersistentVolume
metadata:
  name: slskd-nas-pv
  labels:
    app.kubernetes.io/part-of: slskd
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-slskd
  nfs:
    server: 192.168.1.162
    path: /volume1/docker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-media
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: slskd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-slskd
  resources:
    requests:
      storage: 200Gi
  volumeName: slskd-nas-pv
