apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: slskd
    app.kubernetes.io/part-of: slskd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
