---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-secrets
  namespace: woodpecker
spec:
  encryptedData:
    WOODPECKER_GITHUB_CLIENT: AgC6TT/XHsINJ/KToyAK9oT9eSVTTCD2WZJ0DtmDdkbCFjKKdimxe/2qUcenmOnoCf+NFAmRjbEMgLfjHlvbtUZtDoM6qwbAGCACsmGAEcxhGEb7V1YMdMdOw2f9Dj95vVpAz5Gz/SkQiI2AgsAhB4qz+XHyGzY2rHVj4Zv/jSKMh4vI0JM2BsW5wBVuGP6eYR7UA3HnsgRs9XxiQVXCMUyHSgWTo/0dgtsKvnTtdTMTjZowgUlKID5/F/IUBEm6eYe3r3jI/3mCHJioc/tWj8Eetkqirs05Sy0D5A/R83BaO868dpUPreU2vKL0g8nueBh6mtzJP2HwHXrMRmCi/Vts/C2p5z47YGhHa0Q9Aor8jFKenaHPj/R8PsW3ybVyKHkLqTHZDZlGeuRofodJUdUi5NGM1WIPmkodtwcjHfG2dIsHRD9eMRFZRVKOYslgCmP1UeOY4m6LdG9O5F+b2Iok9I+XqiJPvOXGyfg4TB4X2PlJxdKzD2ex+rpscglDi1sBpg3Z6xPEhOa5bfDCt9i/ymGIbsPwiLc37TM/0FJODNXPwdtMTCwgXXgUeCaL229tY3iGe5saaucFg3eUnOngsOqqJctqAdy+ky/IyGvLHLmuGYJHyfi9sQFnA6ipaP/NwY7BYuC2x1sBWRcDfFBsgRTHFwL7tb/9pN8WrqwGfI7fe3zx0ynoja5tC41zH+ShpXKcWdTNaH3atDiX43vt1c6AZw==
    WOODPECKER_GITHUB_SECRET: AgCb4cLB4ls+QbvWLsA72i7EL2QtcDuZPyOzTj5gqHQRZeAI69sbRAKcFvlI2fQTk+P16j1n9dhbrGcYosQGD6/xRORbypv4qcqjWv9kR8nHmZSDpXa7h4/pOXerc+15L/s+bdKL29PRPqTER9+GSaS0CqIbofnzWzSM6/SxWaKY/EWhjBah0L0eg7ThFsvBwwzljpQ22PMYI2WJIzYABCh/68oigzfwSrBZpFYizzeEUYCUbwsRXV3vwIlXjlJfFoVsgp2WNdSomrFaaDKdpcprIHFl6luMhglj6bYW8tP9S0iYHgTsL1pFbA5uJWFGTdazlirZsl6lPkixpM7qJ9sGR7XCBKZO2HuzUPQ3H/q1wEZerY5xYx4vqL+Z5nGjWh1OblsLBWX6NgfwwCiFbGf3XzTT0jpe7tKvADWbzWJ8K/Hjp9zVSOcNbaHJciUvkOVPzdQUga0IFfGnaVVn+ZTP+K+abn3Imy6DBkaP7XJIjs+/fzTPF7GSGlAI17ITHgcLPH7Sh82fJTj3784i1pBeFxTFyad3wEwLvGoJLS0yT8g8RXbzpo9tMXfsYMdlJsgltxyUscQeFPeQbZ5s7WEdndX2XTuDn19B88H8qlGh07OAB67k03Dq/bz0aX7L/1C9T90WMZLA4Wl8v/uIs6vIQmUXsVdWsxniWmTItXB9kiGKAhLpDlTemMOeJwON/W12vtCoTsqORAwc9pdpl9EyfqQkiZEklaQ2TjrNK1NqL8CBd5JEvwka
  template:
    metadata:
      name: woodpecker-secrets
      namespace: woodpecker
