server:
  service:
    clusterIP: 10.43.55.118
  env:
    WOODPECKER_GITHUB: "true"
    WOODPECKER_HOST: https://wood.pj-home-lab.com
    WOODPECKER_OPEN: "false"
  extraSecretNamesForEnvFrom:
    - woodpecker-secrets
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: woodpecker.lan
        paths:
          - path: /
      - host: wood.pj-home-lab.com
        paths:
          - path: /

agent:
  enabled: true
  replicaCount: 1
  env:
    WOODPECKER_BACKEND_K8S_STORAGE_RWX: "false"
